name: Build Docker Image

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v6
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - name: Run Linter
        run: |
          pip install --no-cache-dir black
          black --check --diff .

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag test-mcp-server:latest
          docker save -o /tmp/docker-image.tar test-mcp-server:latest

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: docker-image
          path: /tmp/docker-image.tar
