name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_job:
    uses: ./.github/workflows/build.yml

  test_job:
    needs: build_job
    uses: ./.github/workflows/test.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
