name: Test MCP Server

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v6
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load < /tmp/docker-image.tar

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install test dependencies
        run: |
          pip install --no-cache-dir pytest requests

      - name: Run tests inside the container
        run: |
          # set env variable
          export GITHUB_TOKEN=${{ secrets.CI_GITHUB_TOKEN }}
          # Start the container in the background
          docker run -e GITHUB_TOKEN="$GITHUB_TOKEN" --rm -d -p 8001:8000 test-mcp-server:latest
          # Give the server a moment to boot
          sleep 5
          # Run tests
          pytest -vv tests/test_mcp.py
